[tool.poetry]
name = "db-gpt"
version = "0.0.6"
description = "Interact with your data and environment privately"
authors = []
readme = "README.md"
license = "MIT"
packages = [{include = "db_gpt"}]
repository = "https://www.github.com/csunny/DB-GPT"

[tool.poetry.dependencies]
python = "^3.10"
accelerate = "^0.16"
torch = "^2.0.0"
aiohttp = "^3.8"
aiosignal = "^1.3"
async-timeout = "^4.0"
attrs = "^22.2"
bitsandbytes = "^0.37"
cchardet = "^2.1"
chardet = "^5.1"
contourpy = "^1.0"
cycler = "^0.11.0"
filelock = "^3.9.0"
fonttools = "^4.38.0"
frozenlist = "^1.3.3"
huggingface-hub = "^0.13.4"
importlib-resources = "^5.12.0"
kiwisolver = "^1.4.4"
matplotlib = "^3.7.0"
multidict = "^6.0.4"
packaging = "^23.0"
psutil = "^5.9.4"
pycocotools = "^2.0.6"
pyparsing = "^3.0.9"
python-dateutil = "^2.8.2"
pyyaml = "^6.0"
tokenizers = "^0.13.2"
tqdm = "^4.64.1"
transformers = "^4.28.0"
timm = "^0.6.13"
spacy = "^3.5.1"
webdataset = "^0.2.48"
yarl = "^1.8.2"
zipp = "^3.14.0"
omegaconf = "^2.3.0"
opencv-python = "^4.7.0.72"
iopath = "^0.1.10"
tenacity = "^8.2.2"
peft = "^0.3"
pycocoevalcap = "^1.2"
cpm_kernels = "^1.0.11"
umap-learn = "^0.5.3"
notebook = "^6.5.4"
gradio = "^3.23"
gradio-client = "^0.0.8"
wandb = "^0.15.2"
llama-index = "^0.5.27"
pymysql = "^1.0.3" 
unstructured = "^0.6.3"
grpcio = "^1.47.5"

auto-gpt-plugin-template = "^1.0.1"
pymdown-extensions = "^9.11"
gTTS = "^2.3.1"
langchain = "^0.0.142"
nltk = "^3.8.1"
python-dotenv = "^1.0.0"
pymilvus = {version = "2.2.1", optional = true} 
vcrpy = "^4.2.1"
chromadb = "^0.3.22"
markdown2 = "^2.4.8"
colorama = "^0.4.6"
playsound = "^1.3"
distro = {version = "1.8.0", optional = true}
pypdf = {version = "^3.4.0", optional = true}

[tool.poetry.group.docs.dependencies]
autodoc_pydantic = "^1.8.0"
myst_parser = "^0.18.1"
nbsphinx = "^0.8.9"
sphinx = "^4.5.0"
sphinx-autobuild = "^2021.3.14"
sphinx_book_theme = "^0.3.3"
sphinx_rtd_theme = "^1.0.0"
sphinx-typlog-theme = "^0.8.0"
sphinx-panels = "^0.6.0"
toml = "^0.10.2"
myst-nb = "^0.17.1"
linkchecker = "^10.2.1"
sphinx-copybutton = "^0.5.1"

[tool.poetry.group.test.dependencies]
# The only dependencies that should be added are
# dependencies used for running tests (e.g., pytest, freezegun, response).
# Any dependencies that do not meet that criteria will be removed.
pytest = "^7.3.0"
pytest-cov = "^4.0.0"
pytest-dotenv = "^0.5.2"
duckdb-engine = "^0.7.0"
pytest-watcher = "^0.2.6"
freezegun = "^1.2.2"
responses = "^0.22.0"
pytest-asyncio = "^0.20.3"
lark = "^1.1.5"
pytest-mock  = "^3.10.0"
pytest-socket = "^0.6.0"


[tool.poetry.group.lint.dependencies]
ruff = "^0.0.249"
types-toml = "^0.10.8.1"
types-redis = "^4.3.21.6"
black = "^23.1.0"
types-chardet = "^5.0.4.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
exclude = [
    ".venv",
    "__pycache__",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".ruff_cache",
    "examples",
    "notebooks",
]
