[tool.poetry]
name = "db-gpt"
version = "0.0.6"
description = "Interact with your data and environment privately"
authors = []
readme = "README.md"
license = "MIT"
packages = [{include = "db_gpt"}]
repository = "https://www.github.com/csunny/DB-GPT"

[tool.mypy]
ignore_missing_imports = "True"
disallow_untyped_defs = "True"
exclude = ["notebooks", "build", "examples"]

[tool.setuptools]
py-modules = []

[tool.ruff]
exclude = [
    ".venv",
    "__pycache__",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".ruff_cache",
    "examples",
    "notebooks",
]